apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: open-webui
  name: open-webui
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:  
      volumes:
      - name: webui-data
        persistentVolumeClaim:
          claimName: ollama-pvc
      containers:
      - image: openwebui/open-webui:latest
        name: open-webui
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_BASE_URL
          value: http://host.docker.internal:11434 # <-- if using local docker and resolve DNS to watching all network
          # value: http://svc-ollama:11434 <-- if using ClusterIP service into k8e k8e
        volumeMounts:
          - name: webui-data
            mountPath: /app/backend/data
        resources:
          requests:
            cpu: 1000m
            memory: 512Mi
          limits: 
            cpu: 2000m
            memory: 3Gi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 120
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 60
